### ISSUE TITLE
I haven't heard back from an internship inquiry.

### ISSUE THREAD

**Issue by joshuarli** [nutshellcrm/join-the-team#2]
Hey Nutshell!

I sent a mail to jobs@nutshell.com inquiring about summer 2017 internship opportunities about a week ago, and haven't received a reply (I'm joshua.r.li.98@gmail.com). I'm hoping this opened issue gets your attention!

**Comment by andyfowler** [comment]
@JoshuaRLi Howdy!! Thanks for being the innovative first post to our issue tracker. I've just sent you an email. Sorry to drag our feet — we've been trying to figure out the right approach to internships this summer!
